### ISSUE TITLE
Not sending messages to discord

### ISSUE THREAD

**Issue by DravenSA** [rudynakodach/WebhookIntegrations#20]
# WI Bug Report Template
Please answer all the questions below to give me clear understanding of what might not work as expected.

## Description
What happened? -  Messages are not sent to discord
Did you get any errors in the console (if yes, send **the entire stack**)?
What version of the plugin are you using?  - 4.2

## Reproduction
Start server 

## Expected behavior
expected discord to say Server Started

## Software Information
 - OS: [e.g. Windows 10] Windows 10 
- Minecraft server's version:  Spigot 1.20
- Plugin version:  WebhookIntegrations v4.2

**Additional notes**
how much of this helps i dont know
```
[12:48:09 INFO]: [WebhookIntegrations] Enabling WebhookIntegrations v4.2
[12:48:09 INFO]: [WebhookIntegrations] Hello, World!
[12:48:09 INFO]: [WebhookIntegrations] Initializing language...
[12:48:09 INFO]: [WebhookIntegrations] Hooked to en_US
[12:48:09 INFO]: [WebhookIntegrations] Thank you for using WebhookIntegrations <3
[12:48:09 INFO]: [WebhookIntegrations] Checking for updates...
[12:48:09 INFO]: [WebhookIntegrations] Already running the latest version!
[12:48:09 INFO]: [WebhookIntegrations] Registering events...
[12:48:09 ERROR]: [WebhookIntegrations] Plugin WebhookIntegrations v4.2 has failed to register events for class rudynakodach.github.io.webhookintegrations.Events.Webhook.OnPlayerChat because io/papermc/paper/event/player/AsyncChatEvent does not exist.
[12:48:09 ERROR]: Error occurred while enabling WebhookIntegrations v4.2 (Is it up to date?)
java.lang.NoClassDefFoundError: net/kyori/adventure/text/Component
	at rudynakodach.github.io.webhookintegrations.WebhookIntegrations.onEnable(WebhookIntegrations.java:149) ~[?:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:266) ~[spigot-api-1.20-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:342) ~[spigot-api-1.20-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:480) ~[spigot-api-1.20-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.craftbukkit.v1_20_R1.CraftServer.enablePlugin(CraftServer.java:541) ~[spigot-1.20-R0.1-SNAPSHOT.jar:3777-Spigot-723951c-f3b2b22]
	at org.bukkit.craftbukkit.v1_20_R1.CraftServer.enablePlugins(CraftServer.java:455) ~[spigot-1.20-R0.1-SNAPSHOT.jar:3777-Spigot-723951c-f3b2b22]
	at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:589) ~[spigot-1.20-R0.1-SNAPSHOT.jar:3777-Spigot-723951c-f3b2b22]
	at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:414) ~[spigot-1.20-R0.1-SNAPSHOT.jar:3777-Spigot-723951c-f3b2b22]
	at net.minecraft.server.dedicated.DedicatedServer.e(DedicatedServer.java:250) ~[spigot-1.20-R0.1-SNAPSHOT.jar:3777-Spigot-723951c-f3b2b22]
	at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:973) ~[spigot-1.20-R0.1-SNAPSHOT.jar:3777-Spigot-723951c-f3b2b22]
	at net.minecraft.server.MinecraftServer.lambda$0(MinecraftServer.java:304) ~[spigot-1.20-R0.1-SNAPSHOT.jar:3777-Spigot-723951c-f3b2b22]
	at java.lang.Thread.run(Thread.java:1623) ~[?:?]

```
also player just joined and this is the error
```
[12:50:26 ERROR]: Could not pass event PlayerJoinEvent to WebhookIntegrations v4.2
org.bukkit.event.EventException: null
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:310) ~[spigot-api-1.20-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[spigot-api-1.20-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:589) ~[spigot-api-1.20-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:576) ~[spigot-api-1.20-R0.1-SNAPSHOT.jar:?]
	at net.minecraft.server.players.PlayerList.a(PlayerList.java:308) ~[spigot-1.20-R0.1-SNAPSHOT.jar:3777-Spigot-723951c-f3b2b22]
	at net.minecraft.server.network.LoginListener.a(LoginListener.java:183) ~[spigot-1.20-R0.1-SNAPSHOT.jar:3777-Spigot-723951c-f3b2b22]
	at net.minecraft.server.network.LoginListener.d(LoginListener.java:169) ~[spigot-1.20-R0.1-SNAPSHOT.jar:3777-Spigot-723951c-f3b2b22]
	at net.minecraft.server.network.LoginListener.c(LoginListener.java:75) ~[spigot-1.20-R0.1-SNAPSHOT.jar:3777-Spigot-723951c-f3b2b22]
	at net.minecraft.network.NetworkManager.a(NetworkManager.java:279) ~[spigot-1.20-R0.1-SNAPSHOT.jar:3777-Spigot-723951c-f3b2b22]
	at net.minecraft.server.network.ServerConnection.c(ServerConnection.java:175) ~[spigot-1.20-R0.1-SNAPSHOT.jar:3777-Spigot-723951c-f3b2b22]
	at net.minecraft.server.MinecraftServer.b(MinecraftServer.java:1324) ~[spigot-1.20-R0.1-SNAPSHOT.jar:3777-Spigot-723951c-f3b2b22]
	at net.minecraft.server.dedicated.DedicatedServer.b(DedicatedServer.java:388) ~[spigot-1.20-R0.1-SNAPSHOT.jar:3777-Spigot-723951c-f3b2b22]
	at net.minecraft.server.MinecraftServer.a(MinecraftServer.java:1198) ~[spigot-1.20-R0.1-SNAPSHOT.jar:3777-Spigot-723951c-f3b2b22]
	at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:1015) ~[spigot-1.20-R0.1-SNAPSHOT.jar:3777-Spigot-723951c-f3b2b22]
	at net.minecraft.server.MinecraftServer.lambda$0(MinecraftServer.java:304) ~[spigot-1.20-R0.1-SNAPSHOT.jar:3777-Spigot-723951c-f3b2b22]
	at java.lang.Thread.run(Thread.java:1623) ~[?:?]
Caused by: java.lang.NullPointerException: Cannot invoke "rudynakodach.github.io.webhookintegrations.Modules.MessageConfiguration.canAnnounce(String)" because the return value of "rudynakodach.github.io.webhookintegrations.Modules.MessageConfiguration.get()" is null
	at rudynakodach.github.io.webhookintegrations.Events.Webhook.OnPlayerJoin.onPlayerJoinEvent(OnPlayerJoin.java:42) ~[?:?]
	at jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:578) ~[?:?]
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:306) ~[spigot-api-1.20-R0.1-SNAPSHOT.jar:?]
	... 15 more


```

and then even more

```
[12:50:26 ERROR]: Could not pass event PlayerAdvancementDoneEvent to WebhookIntegrations v4.2
org.bukkit.event.EventException: null
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:310) ~[spigot-api-1.20-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[spigot-api-1.20-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:589) ~[spigot-api-1.20-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:576) ~[spigot-api-1.20-R0.1-SNAPSHOT.jar:?]
	at net.minecraft.server.AdvancementDataPlayer.a(AdvancementDataPlayer.java:235) ~[spigot-1.20-R0.1-SNAPSHOT.jar:3777-Spigot-723951c-f3b2b22]
	at net.minecraft.advancements.CriterionTrigger$a.a(SourceFile:35) ~[spigot-1.20-R0.1-SNAPSHOT.jar:3777-Spigot-723951c-f3b2b22]
	at net.minecraft.advancements.critereon.CriterionTriggerAbstract.a(SourceFile:74) ~[spigot-1.20-R0.1-SNAPSHOT.jar:3777-Spigot-723951c-f3b2b22]
	at net.minecraft.advancements.critereon.PlayerTrigger.a(SourceFile:30) ~[spigot-1.20-R0.1-SNAPSHOT.jar:3777-Spigot-723951c-f3b2b22]
	at net.minecraft.server.level.EntityPlayer.l(EntityPlayer.java:649) ~[spigot-1.20-R0.1-SNAPSHOT.jar:3777-Spigot-723951c-f3b2b22]
	at net.minecraft.server.level.WorldServer.a(WorldServer.java:865) ~[spigot-1.20-R0.1-SNAPSHOT.jar:3777-Spigot-723951c-f3b2b22]
	at net.minecraft.world.level.World.a(World.java:682) ~[spigot-1.20-R0.1-SNAPSHOT.jar:3777-Spigot-723951c-f3b2b22]
	at net.minecraft.server.level.WorldServer.lambda$12(WorldServer.java:443) ~[spigot-1.20-R0.1-SNAPSHOT.jar:3777-Spigot-723951c-f3b2b22]
	at net.minecraft.world.level.entity.EntityTickList.a(SourceFile:54) ~[spigot-1.20-R0.1-SNAPSHOT.jar:3777-Spigot-723951c-f3b2b22]
	at net.minecraft.server.level.WorldServer.a(WorldServer.java:423) ~[spigot-1.20-R0.1-SNAPSHOT.jar:3777-Spigot-723951c-f3b2b22]
	at net.minecraft.server.MinecraftServer.b(MinecraftServer.java:1302) ~[spigot-1.20-R0.1-SNAPSHOT.jar:3777-Spigot-723951c-f3b2b22]
	at net.minecraft.server.dedicated.DedicatedServer.b(DedicatedServer.java:388) ~[spigot-1.20-R0.1-SNAPSHOT.jar:3777-Spigot-723951c-f3b2b22]
	at net.minecraft.server.MinecraftServer.a(MinecraftServer.java:1198) ~[spigot-1.20-R0.1-SNAPSHOT.jar:3777-Spigot-723951c-f3b2b22]
	at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:1015) ~[spigot-1.20-R0.1-SNAPSHOT.jar:3777-Spigot-723951c-f3b2b22]
	at net.minecraft.server.MinecraftServer.lambda$0(MinecraftServer.java:304) ~[spigot-1.20-R0.1-SNAPSHOT.jar:3777-Spigot-723951c-f3b2b22]
	at java.lang.Thread.run(Thread.java:1623) ~[?:?]
Caused by: java.lang.NullPointerException: Cannot invoke "rudynakodach.github.io.webhookintegrations.Modules.MessageConfiguration.canAnnounce(String)" because the return value of "rudynakodach.github.io.webhookintegrations.Modules.MessageConfiguration.get()" is null
	at rudynakodach.github.io.webhookintegrations.Events.Webhook.OnPlayerAdvancementCompleted.onAdvancementMade(OnPlayerAdvancementCompleted.java:43) ~[?:?]
	at jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:578) ~[?:?]
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:306) ~[spigot-api-1.20-R0.1-SNAPSHOT.jar:?]
	... 19 more

```

and this repeats several times like at least 6 times

**Comment by DravenSA** [comment]
Have added more info to the original post if it helps

**Comment by rudynakodach** [comment]
Sadly Spigot is not supported by this plugin. It was made using the PaperMC API. You can try migrating to PaperMC - they support Spigot plugins, but Spigot doesn't support PaperMC plugins. If you really want to stick to Spigot, the Spigot Adventure Platform is your way to go.

**Comment by DravenSA** [comment]
I was on PaperMC, but 1.20 came out and Paper has not updated to 1.20 yet, hence we moved over to spigot. 
Can you explain what "Spigot Adventure Platform" is and will it webhook to discord?

**Comment by rudynakodach** [comment]
Spigot Adventure Platform is a fork of Spigot with the Adventure API implemented. https://github.com/KyoriPowered/adventure-platform

Also, there is already an experimental version of PaperMC for 1.20 released [here](https://github.com/PaperMC/Paper/pull/9285).

**Comment by rudynakodach** [comment]
I'm assuming that the plugin is working fine after migration. If something's wrong, feel free to open a new bug report.
