### ISSUE TITLE
WI help needed

### ISSUE THREAD

**Issue by alexandreasj** [rudynakodach/WebhookIntegrations#23]
# Support
Please tell me what you are struggling with.

hello,

I'm using version 1.19.4 of mohist, I installed the same version of the plugin but I'm getting this error in the console:

e
[21:53:47 ERROR]: Could not pass event PlayerAdvancementDoneEvent to WebhookIntegrations v4.3.1
org.bukkit.event.EventException: null
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:303) ~[forge-1.19.4-45.1.6-universal.jar%23186!/:?]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[forge-1.19.4-45.1.6-universal.jar%23186!/:?]
        at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:588) ~[forge-1.19.4-45.1.6-universal.jar%23186!/:?]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:575) ~[forge-1.19.4-45.1.6-universal.jar%23186!/:?]
        at com.mohistmc.eventhandler.dispatcher.PlayerEventDispatcher.onAdvancementDone(PlayerEventDispatcher.java:33) ~[forge-1.19.4-45.1.6-universal.jar%23186!/:?]
        at com.mohistmc.eventhandler.dispatcher.__PlayerEventDispatcher_onAdvancementDone_AdvancementEvent.invoke(.dynamic) ~[forge-1.19.4-45.1.6-universal.jar%23186!/:?]
        at net.minecraftforge.eventbus.ASMEventHandler.invoke(ASMEventHandler.java:73) ~[eventbus-6.0.3.jar%2379!/:?]
        at net.minecraftforge.eventbus.EventBus.post(EventBus.java:315) ~[eventbus-6.0.3.jar%2379!/:?]
        at net.minecraftforge.eventbus.EventBus.post(EventBus.java:296) ~[eventbus-6.0.3.jar%2379!/:?]
        at net.minecraftforge.common.ForgeHooks.onAdvancement(ForgeHooks.java:1010) ~[forge-1.19.4-45.1.6-universal.jar%23186!/:?]
        at net.minecraft.server.PlayerAdvancements.m_135988_(PlayerAdvancements.java:191) ~[server-1.19.4-20230314.122934-srg.jar%23181!/:?]
        at net.minecraft.advancements.CriterionTrigger$Listener.m_13686_(CriterionTrigger.java:35) ~[server-1.19.4-20230314.122934-srg.jar%23181!/:?]
        at net.minecraft.advancements.critereon.SimpleCriterionTrigger.m_66234_(SimpleCriterionTrigger.java:74) ~[server-1.19.4-20230314.122934-srg.jar%23181!/:?]
        at net.minecraft.advancements.critereon.InventoryChangeTrigger.m_43153_(InventoryChangeTrigger.java:55) ~[server-1.19.4-20230314.122934-srg.jar%23181!/:?]
        at net.minecraft.advancements.critereon.InventoryChangeTrigger.m_43149_(InventoryChangeTrigger.java:51) ~[server-1.19.4-20230314.122934-srg.jar%23181!/:?]
        at net.minecraft.server.level.ServerPlayer$2.m_7934_(ServerPlayer.java:262) ~[server-1.19.4-20230314.122934-srg.jar%23181!/:?]
        at net.minecraft.world.inventory.AbstractContainerMenu.m_150407_(AbstractContainerMenu.java:332) ~[server-1.19.4-20230314.122934-srg.jar%23181!/:?]
        at net.minecraft.world.inventory.AbstractContainerMenu.m_38946_(AbstractContainerMenu.java:284) ~[server-1.19.4-20230314.122934-srg.jar%23181!/:?]
        at net.minecraft.server.level.ServerPlayer.m_7938_(ServerPlayer.java:1109) ~[server-1.19.4-20230314.122934-srg.jar%23181!/:?]
        at net.minecraft.world.entity.item.ItemEntity.m_6123_(ItemEntity.java:441) ~[server-1.19.4-20230314.122934-srg.jar%23181!/:?]
        at net.minecraft.world.entity.player.Player.m_36277_(Player.java:587) ~[server-1.19.4-20230314.122934-srg.jar%23181!/:?]
        at net.minecraft.world.entity.player.Player.m_8107_(Player.java:554) ~[server-1.19.4-20230314.122934-srg.jar%23181!/:?]
        at net.minecraft.world.entity.LivingEntity.m_8119_(LivingEntity.java:2718) ~[server-1.19.4-20230314.122934-srg.jar%23181!/:?]
        at net.minecraft.world.entity.player.Player.m_8119_(Player.java:261) ~[server-1.19.4-20230314.122934-srg.jar%23181!/:?]
        at net.minecraft.server.level.ServerPlayer.m_9240_(ServerPlayer.java:605) ~[server-1.19.4-20230314.122934-srg.jar%23181!/:?]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.m_9933_(ServerGamePacketListenerImpl.java:344) ~[server-1.19.4-20230314.122934-srg.jar%23181!/:?]
        at net.minecraft.network.Connection.m_129483_(Connection.java:263) ~[server-1.19.4-20230314.122934-srg.jar%23181!/:?]
        at net.minecraft.server.network.ServerConnectionListener.m_9721_(ServerConnectionListener.java:153) ~[server-1.19.4-20230314.122934-srg.jar%23181!/:?]
        at net.minecraft.server.MinecraftServer.m_5703_(MinecraftServer.java:1284) ~[server-1.19.4-20230314.122934-srg.jar%23181!/:?]
        at net.minecraft.server.dedicated.DedicatedServer.m_5703_(DedicatedServer.java:339) ~[server-1.19.4-20230314.122934-srg.jar%23181!/:?]
        at net.minecraft.server.MinecraftServer.m_5705_(MinecraftServer.java:1173) ~[server-1.19.4-20230314.122934-srg.jar%23181!/:?]
        at net.minecraft.server.MinecraftServer.m_130011_(MinecraftServer.java:1001) ~[server-1.19.4-20230314.122934-srg.jar%23181!/:?]
        at net.minecraft.server.MinecraftServer.m_206580_(MinecraftServer.java:298) ~[server-1.19.4-20230314.122934-srg.jar%23181!/:?]
        at java.lang.Thread.run(Thread.java:833) [?:?]
Caused by: java.lang.NullPointerException: Cannot invoke "rudynakodach.github.io.webhookintegrations.Modules.MessageConfiguration.canAnnounce(String)" because the return value of "rudynakodach.github.io.webhookintegrations.Modules.MessageConfiguration.get()" is null
        at rudynakodach.github.io.webhookintegrations.Events.Game.OnPlayerAdvancementCompleted.onAdvancementMade(OnPlayerAdvancementCompleted.java:43) ~[?:?]
        at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
        at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?]
        at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
        at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?]
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:301) ~[forge-1.19.4-45.1.6-universal.jar%23186!/:?]

Would you help me?

**Comment by alexandreasj** [comment]
I found the solution in a closed issue. I'm using spigot :c
