### ISSUE TITLE
I'm getting this error in console...

### ISSUE THREAD

**Issue by ga6rielsilva** [rudynakodach/WebhookIntegrations#4]
```
[01:55:36 INFO]: [WebhookIntegrations] Enabling WebhookIntegrations v2.1
[01:55:36 INFO]: [WebhookIntegrations] Hello, World!
[01:55:36 INFO]: [WebhookIntegrations] Initializing language...
[01:55:36 INFO]: [WebhookIntegrations] Hooked to en_US
[01:55:36 INFO]: [WebhookIntegrations] Checking for updates...
[01:55:37 ERROR]: Error occurred while enabling WebhookIntegrations v2.1 (Is it up to date?)
java.lang.NoSuchMethodError: 'long kotlin.time.DurationKt.toDuration(int, kotlin.time.DurationUnit)'
        at okhttp3.internal._CacheControlCommonKt.commonMaxStale(-CacheControlCommon.kt:56) ~[?:?]
        at okhttp3.CacheControl$Builder.maxStale(CacheControl.kt:155) ~[?:?]
        at okhttp3.internal._CacheControlCommonKt.commonForceCache(-CacheControlCommon.kt:80) ~[?:?]
        at okhttp3.CacheControl.<clinit>(CacheControl.kt:207) ~[?:?]
        at okhttp3.Request.cacheControl(Request.kt:116) ~[?:?]
        at okhttp3.internal.cache.CacheStrategy$Factory.compute(CacheStrategy.kt:134) ~[?:?]
        at okhttp3.internal.cache.CacheInterceptor.intercept(CacheInterceptor.kt:52) ~[?:?]
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109) ~[?:?]
        at okhttp3.internal.http.BridgeInterceptor.intercept(BridgeInterceptor.kt:84) ~[?:?]
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109) ~[?:?]
        at okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(RetryAndFollowUpInterceptor.kt:65) ~[?:?]
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109) ~[?:?]
        at okhttp3.internal.connection.RealCall.getResponseWithInterceptorChain$okhttp(RealCall.kt:205) ~[?:?]
        at okhttp3.internal.connection.RealCall.execute(RealCall.kt:158) ~[?:?]
        at rudynakodach.github.io.webhookintegrations.WebhookIntegrations.getVersion(WebhookIntegrations.java:204) ~[?:?]
        at rudynakodach.github.io.webhookintegrations.WebhookIntegrations.onEnable(WebhookIntegrations.java:54) ~[?:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:263) ~[forge:?]
        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:335) ~[forge:?]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:479) ~[forge:?]
        at org.bukkit.craftbukkit.v1_16_R3.CraftServer.enablePlugin(CraftServer.java:503) ~[forge:7e29f765-296df566-9fb885e8]
        at org.bukkit.craftbukkit.v1_16_R3.CraftServer.enablePlugins(CraftServer.java:415) ~[forge:7e29f765-296df566-9fb885e8]
        at net.minecraft.server.MinecraftServer.func_240787_a_(MinecraftServer.java:428) ~[?:?]
        at net.minecraft.server.MinecraftServer.func_240800_l__(MinecraftServer.java:348) ~[?:?]
        at net.minecraft.server.dedicated.DedicatedServer.func_71197_b(DedicatedServer.java:221) ~[?:?]
        at net.minecraft.server.MinecraftServer.func_240802_v_(MinecraftServer.java:770) ~[?:?]
        at net.minecraft.server.MinecraftServer.func_240783_a_(MinecraftServer.java:268) ~[?:?]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]
[01:55:37 INFO]: [WebhookIntegrations] Disabling WebhookIntegrations v2.1
[01:55:37 INFO]: [WebhookIntegrations] this is my final message
[01:55:37 INFO]: [WebhookIntegrations] goodb ye
```

WebhookIntegrations v2.1
Mohist: 1.16.5
Java: 17

**Comment by rudynakodach** [comment]
I'm looking into that, hold tight!

**Comment by rudynakodach** [comment]
Hello.
Thanks for waiting patiently.
I'm still working on resolving your issue, even that I don't see any faulty code. I may have just found what the issue might be.

MohistMC might not contain the Kotlin language definitions and you might need to download the Kotlin mod [here](https://www.curseforge.com/minecraft/mc-mods/kotlin-for-forge)

Can you please check if the plugin works with that mod installed?

**Comment by ga6rielsilva** [comment]
Unfortunately it didn't work... I installed the mod you said, and I'm using version 2.2

```
[14:12:24] [Server thread/INFO] [rudynakodach.github.io.webhookintegrations.WebhookIntegrations/]: [WebhookIntegrations] Enabling WebhookIntegrations v2.2
[14:12:24] [Server thread/INFO] [rudynakodach.github.io.webhookintegrations.WebhookIntegrations/]: [WebhookIntegrations] Hello, World!
[14:12:24] [Server thread/WARN] [rudynakodach.github.io.webhookintegrations.WebhookIntegrations/]: [WebhookIntegrations] Could not save lang.yml to plugins/WebhookIntegrations/lang.yml because lang.yml already exists.
[14:12:24] [Server thread/INFO] [rudynakodach.github.io.webhookintegrations.WebhookIntegrations/]: [WebhookIntegrations] Initializing language...
[14:12:24] [Server thread/INFO] [rudynakodach.github.io.webhookintegrations.WebhookIntegrations/]: [WebhookIntegrations] Hooked to en_US
[14:12:24] [Server thread/INFO] [rudynakodach.github.io.webhookintegrations.WebhookIntegrations/]: [WebhookIntegrations] Checking for updates...
[14:12:25] [Server thread/ERROR] [Minecraft/]: Error occurred while enabling WebhookIntegrations v2.2 (Is it up to date?)
java.lang.NoSuchMethodError: 'long kotlin.time.DurationKt.toDuration(int, kotlin.time.DurationUnit)'
	at okhttp3.internal._CacheControlCommonKt.commonMaxStale(-CacheControlCommon.kt:56) ~[?:?]
	at okhttp3.CacheControl$Builder.maxStale(CacheControl.kt:155) ~[?:?]
	at okhttp3.internal._CacheControlCommonKt.commonForceCache(-CacheControlCommon.kt:80) ~[?:?]
	at okhttp3.CacheControl.<clinit>(CacheControl.kt:207) ~[?:?]
	at okhttp3.Request.cacheControl(Request.kt:116) ~[?:?]
	at okhttp3.internal.cache.CacheStrategy$Factory.compute(CacheStrategy.kt:134) ~[?:?]
	at okhttp3.internal.cache.CacheInterceptor.intercept(CacheInterceptor.kt:52) ~[?:?]
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109) ~[?:?]
	at okhttp3.internal.http.BridgeInterceptor.intercept(BridgeInterceptor.kt:84) ~[?:?]
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109) ~[?:?]
	at okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(RetryAndFollowUpInterceptor.kt:65) ~[?:?]
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109) ~[?:?]
	at okhttp3.internal.connection.RealCall.getResponseWithInterceptorChain$okhttp(RealCall.kt:205) ~[?:?]
	at okhttp3.internal.connection.RealCall.execute(RealCall.kt:158) ~[?:?]
	at rudynakodach.github.io.webhookintegrations.AutoUpdater.getLatestVersion(AutoUpdater.java:120) ~[?:?]
	at rudynakodach.github.io.webhookintegrations.WebhookIntegrations.onEnable(WebhookIntegrations.java:54) ~[?:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:263) ~[forge:?]
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:335) ~[forge:?]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:479) ~[forge:?]
	at org.bukkit.craftbukkit.v1_16_R3.CraftServer.enablePlugin(CraftServer.java:503) ~[forge:7e29f765-296df566-9fb885e8]
	at org.bukkit.craftbukkit.v1_16_R3.CraftServer.enablePlugins(CraftServer.java:415) ~[forge:7e29f765-296df566-9fb885e8]
	at net.minecraft.server.MinecraftServer.func_240787_a_(MinecraftServer.java:428) ~[?:?]
	at net.minecraft.server.MinecraftServer.func_240800_l__(MinecraftServer.java:348) ~[?:?]
	at net.minecraft.server.dedicated.DedicatedServer.func_71197_b(DedicatedServer.java:221) ~[?:?]
	at net.minecraft.server.MinecraftServer.func_240802_v_(MinecraftServer.java:770) ~[?:?]
	at net.minecraft.server.MinecraftServer.func_240783_a_(MinecraftServer.java:268) ~[?:?]
	at java.lang.Thread.run(Thread.java:833) ~[?:?]
[14:12:25] [Server thread/INFO] [rudynakodach.github.io.webhookintegrations.WebhookIntegrations/]: [WebhookIntegrations] Disabling WebhookIntegrations v2.2
[14:12:25] [Server thread/ERROR] [Minecraft/]: Error occurred while disabling WebhookIntegrations v2.2 (Is it up to date?)
java.lang.NoClassDefFoundError: Could not initialize class okhttp3.CacheControl
	at okhttp3.Request.cacheControl(Request.kt:116) ~[?:?]
	at okhttp3.internal.cache.CacheStrategy$Factory.compute(CacheStrategy.kt:134) ~[?:?]
	at okhttp3.internal.cache.CacheInterceptor.intercept(CacheInterceptor.kt:52) ~[?:?]
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109) ~[?:?]
	at okhttp3.internal.http.BridgeInterceptor.intercept(BridgeInterceptor.kt:84) ~[?:?]
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109) ~[?:?]
	at okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(RetryAndFollowUpInterceptor.kt:65) ~[?:?]
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109) ~[?:?]
	at okhttp3.internal.connection.RealCall.getResponseWithInterceptorChain$okhttp(RealCall.kt:205) ~[?:?]
	at okhttp3.internal.connection.RealCall.execute(RealCall.kt:158) ~[?:?]
	at rudynakodach.github.io.webhookintegrations.WebhookIntegrations.onDisable(WebhookIntegrations.java:181) ~[?:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:265) ~[forge:?]
	at org.bukkit.plugin.java.JavaPluginLoader.disablePlugin(JavaPluginLoader.java:370) ~[forge:?]
	at org.bukkit.plugin.SimplePluginManager.disablePlugin(SimplePluginManager.java:511) ~[forge:?]
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:339) ~[forge:?]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:479) ~[forge:?]
	at org.bukkit.craftbukkit.v1_16_R3.CraftServer.enablePlugin(CraftServer.java:503) ~[forge:7e29f765-296df566-9fb885e8]
	at org.bukkit.craftbukkit.v1_16_R3.CraftServer.enablePlugins(CraftServer.java:415) ~[forge:7e29f765-296df566-9fb885e8]
	at net.minecraft.server.MinecraftServer.func_240787_a_(MinecraftServer.java:428) ~[?:?]
	at net.minecraft.server.MinecraftServer.func_240800_l__(MinecraftServer.java:348) ~[?:?]
	at net.minecraft.server.dedicated.DedicatedServer.func_71197_b(DedicatedServer.java:221) ~[?:?]
	at net.minecraft.server.MinecraftServer.func_240802_v_(MinecraftServer.java:770) ~[?:?]
	at net.minecraft.server.MinecraftServer.func_240783_a_(MinecraftServer.java:268) ~[?:?]
	at java.lang.Thread.run(Thread.java:833) ~[?:?]
```

**Comment by rudynakodach** [comment]
I will try to rewrite the HTTP related code. For now the best thing you can do is to disable auto-update in the config.

I will fix this issue as fast as possible.

**Comment by rudynakodach** [comment]
Try updating now and check if everything is working. _It should I think_
